/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TonyAdminRouteImport } from './routes/tony-admin'
import { Route as IndexRouteImport } from './routes/index'

const TonyAdminRoute = TonyAdminRouteImport.update({
  id: '/tony-admin',
  path: '/tony-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tony-admin': typeof TonyAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tony-admin': typeof TonyAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tony-admin': typeof TonyAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tony-admin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tony-admin'
  id: '__root__' | '/' | '/tony-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TonyAdminRoute: typeof TonyAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tony-admin': {
      id: '/tony-admin'
      path: '/tony-admin'
      fullPath: '/tony-admin'
      preLoaderRoute: typeof TonyAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TonyAdminRoute: TonyAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
